pluginManagement {
    includeBuild("../release-tools")
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    versionCatalogs {
        libs {
            from(files("../release-tools/gradle/libs.versions.toml"))
        }
    }
}
rootProject.name = "Tetris"
include ':app'
